package com.pushtorefresh.storio.sample.db.entities;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.pushtorefresh.storio.sample.db.tables.AntsTable;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;

@StorIOSQLiteType(table = AntsTable.TABLE)
public class Ant {

    /**
     * If object was not inserted into db, id will be null
     */
    @Nullable
    @StorIOSQLiteColumn(name = AntsTable.COLUMN_ID, key = true)
    Long id;

    @Nullable
    @StorIOSQLiteColumn(name = AntsTable.COLUMN_ID_QUEEN)
    Long idQueen;

    @NonNull
    @StorIOSQLiteColumn(name = AntsTable.COLUMN_NAME)
    String name = "";

    // leave default constructor for AutoGenerated code!
    Ant() {}

    private Ant(@Nullable Long id, @NonNull String name, @Nullable Long idQueen) {
        this.id         = id;
        this.name       = name;
        this.idQueen    = idQueen;
    }

    @NonNull
    public static Ant newAnt(@Nullable Long id, @NonNull String name, @NonNull Long idQueen) {
        return new Ant(id, name, idQueen);
    }

    @NonNull
    public static Ant newAnt(@NonNull String name, @NonNull Long idQueen) {
        return newAnt(null, name, idQueen);
    }

    @NonNull
    public static Ant newAnt(@Nullable Long id, @NonNull String name) {
        return newAnt(id, name, null);
    }

    @NonNull
    public static Ant newAnt(@NonNull String name) {
        return newAnt(null, name);
    }

    @Nullable
    public Long getId() {
        return id;
    }

    public void setId(@Nullable Long id) {
        this.id = id;
    }

    @Nullable
    public Long getIdQueen() {
        return idQueen;
    }

    public void setIdQueen(@Nullable Long idQueen) {
        this.idQueen = idQueen;
    }

    @NonNull
    public String getName() {
        return name;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }
}
