package com.pushtorefresh.storio.sample.db.entities;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.pushtorefresh.storio.sample.db.tables.CarsTable;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;

@StorIOSQLiteType(table = CarsTable.TABLE)
public class Car {

    /**
     * If object was not inserted into db, id will be null
     */
    @Nullable
    @StorIOSQLiteColumn(name = CarsTable.COLUMN_ID, key = true)
    Long id;

    @Nullable
    @StorIOSQLiteColumn(name = CarsTable.COLUMN_ID_PERSON)
    Long idPerson;

    @NonNull
    @StorIOSQLiteColumn(name = CarsTable.COLUMN_MODEL)
    String model = "";

    // leave default constructor for AutoGenerated code!
    Car() {}

    @NonNull
    public static Car newCar(@Nullable Long id, @Nullable Long idPerson, @NonNull String model) {
        Car car = new Car();
        car.id = id;
        car.idPerson = idPerson;
        car.model = model;
        return car;
    }

    @Nullable
    public Long getId() {
        return id;
    }

    public void setId(@Nullable Long id) {
        this.id = id;
    }

    @Nullable
    public Long getIdPerson() {
        return idPerson;
    }

    public void setIdPerson(@Nullable Long idPerson) {
        this.idPerson = idPerson;
    }

    @NonNull
    public String getModel() {
        return model;
    }

    public void setModel(@NonNull String model) {
        this.model = model;
    }
}
