package com.pushtorefresh.storio.sample.db.entities;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.pushtorefresh.storio.sample.db.tables.CarsTable;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;

@StorIOSQLiteType(table = CarsTable.TABLE)
public class Car {

    /**
     * If object was not inserted into db, id will be null
     */
    @Nullable
    @StorIOSQLiteColumn(name = CarsTable.COLUMN_ID, key = true)
    Long id;

    @Nullable
    @StorIOSQLiteColumn(name = CarsTable.COLUMN_ID_PERSON)
    Long idPerson;

    @NonNull
    @StorIOSQLiteColumn(name = CarsTable.COLUMN_MODEL)
    String model = "";

    // leave default constructor for AutoGenerated code!
    Car() {}

    private Car(@Nullable Long id, @NonNull String model, @Nullable Long idPerson) {
        this.id         = id;
        this.model      = model;
        this.idPerson   = idPerson;
    }

    @NonNull
    public static Car newCar(@Nullable Long id, @NonNull String model, @NonNull Long idPerson) {
        return new Car(id, model, idPerson);
    }

    @NonNull
    public static Car newCar(@NonNull String model, @NonNull Long idPerson) {
        return newCar(null, model, idPerson);
    }

    @NonNull
    public static Car newCar(@Nullable Long id, @NonNull String model) {
        return newCar(id, model, null);
    }

    @NonNull
    public static Car newCar(@NonNull String model) {
        return newCar(null, model);
    }

    @Nullable
    public Long getId() {
        return id;
    }

    public void setId(@Nullable Long id) {
        this.id = id;
    }

    @Nullable
    public Long getIdPerson() {
        return idPerson;
    }

    public void setIdPerson(@Nullable Long idPerson) {
        this.idPerson = idPerson;
    }

    @NonNull
    public String getModel() {
        return model;
    }

    public void setModel(@NonNull String model) {
        this.model = model;
    }
}
