package com.pushtorefresh.storio.sample.db.entities;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.pushtorefresh.storio.sample.db.tables.PersonsTable;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;

import java.util.ArrayList;
import java.util.List;

@StorIOSQLiteType(table = PersonsTable.TABLE)
public class Person {

    /**
     * If object was not inserted into db, id will be null
     */
    @Nullable
    @StorIOSQLiteColumn(name = PersonsTable.COLUMN_ID, key = true)
    Long id;

    // For example: "artem_zin", without "@".
    @NonNull
    @StorIOSQLiteColumn(name = PersonsTable.COLUMN_NICK)
    String nick;

    @NonNull
    List<Car> cars = new ArrayList<Car>();

    // leave default constructor for AutoGenerated code!
    Person() {}

    @NonNull
    public static Person newPerson(@Nullable Long id, @NonNull String nick) {
        Person person = new Person();
        person.id = id;
        person.nick = nick;
        return person;
    }

    @Nullable
    public Long getId() {
        return id;
    }

    public void setId(@Nullable Long id) {
        this.id = id;
    }

    @NonNull
    public String getNick() {
        return nick;
    }

    public void setNick(@NonNull String nick) {
        this.nick = nick;
    }

    @NonNull
    public List<Car> getCars() {
        return cars;
    }

    public void setCars(@NonNull List<Car> cars) {
        this.cars = cars;
    }
}
