name: Android Unit Test CI
on:
  push:
    branches:
      - '*'
jobs:
  unit_test:
    name: android_unit_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: run java unit tests
        run: ./gradlew test
